/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package railway;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author kk
 */
public class forgetpass extends javax.swing.JFrame {

 
    public forgetpass() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        answer = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        EorP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        process = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        see1 = new javax.swing.JCheckBox();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("ENTER NEW PASSWORD");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 490, -1, 40));

        answer.setText("Answer");
        answer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                answerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                answerMouseEntered(evt);
            }
        });
        answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerActionPerformed(evt);
            }
        });
        jPanel2.add(answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 410, 410, 60));
        jPanel2.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 540, 420, 65));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("FORGET PASSWORD");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 190, -1, 50));

        EorP.setText("ENTER EMAIL OR PHONE NUMBER");
        EorP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EorPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EorPMouseEntered(evt);
            }
        });
        EorP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EorPActionPerformed(evt);
            }
        });
        jPanel2.add(EorP, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 240, 410, 60));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HAH RAILWAY  RESERVATION SYSTEM");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        process.setBackground(new java.awt.Color(0, 204, 204));
        process.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        process.setForeground(new java.awt.Color(255, 255, 255));
        process.setText("PROCESS");
        process.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processActionPerformed(evt);
            }
        });
        jPanel2.add(process, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 670, 163, 60));

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setText("QUESTION: What is your favorite food?");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 320, 410, 60));

        see1.setBackground(new java.awt.Color(0, 204, 204));
        see1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        see1.setForeground(new java.awt.Color(255, 255, 255));
        see1.setText("Show Password");
        see1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                see1ActionPerformed(evt);
            }
        });
        jPanel2.add(see1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 560, -1, -1));

        back.setBackground(new java.awt.Color(0, 204, 204));
        back.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel2.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 730, 163, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railway/trainlogin.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 2070, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void answerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_answerMouseClicked
        // TODO add your handling code here:
        answer.setText("");
    }//GEN-LAST:event_answerMouseClicked

    private void answerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_answerMouseEntered
        // TODO add your handling code here:
        if(answer.getText().trim().isEmpty()){
            answer.setText("ANSWER");
        }
    }//GEN-LAST:event_answerMouseEntered

    private void answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerActionPerformed

    private void EorPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EorPMouseClicked
        // TODO add your handling code here:
        EorP.setText("");
    }//GEN-LAST:event_EorPMouseClicked

    private void EorPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EorPMouseEntered
        // TODO add your handling code here:
        if(EorP.getText().trim().isEmpty()){
            EorP.setText("ENTER EMAIL OR PHONE NUMBER");
         }
    }//GEN-LAST:event_EorPMouseEntered

    private void EorPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EorPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EorPActionPerformed

    private void processActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processActionPerformed
        // TODO add your handling code here:
        dbconnect go= new dbconnect();
      
        if(EorP.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "Enter Email or Phone Number", "Forget Password",2);
                
            }
           
             else if(answer.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "Enter Answer", "Forget Password",2);
                
            }
             
               else if(pass.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Enter New Password", "Forget Password",2);
                
            }
         
           else 
            {
               
               if(go.updatepass(pass.getText(), EorP.getText(), answer.getText())==1)
                {
                JOptionPane.showMessageDialog(this, "Information Matched and Password Reset", "Forget Password",1);
                signin log= new signin();
                log.setVisible(true);
                dispose();
                }
                else
                {
                                    JOptionPane.showMessageDialog(this, " Information Not Matched", "Forget Password",2);

                }
            }
            
    }//GEN-LAST:event_processActionPerformed

    private void see1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_see1ActionPerformed
        // TODO add your handling code here:
        if(see1.isSelected()){
            pass.setEchoChar((char)0);
        }
        else
        {
            pass.setEchoChar('*');
        }
    }//GEN-LAST:event_see1ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        signin go=new signin();
        go.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgetpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgetpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgetpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgetpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgetpass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EorP;
    private javax.swing.JTextField answer;
    private javax.swing.JButton back;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField pass;
    private javax.swing.JButton process;
    private javax.swing.JCheckBox see1;
    // End of variables declaration//GEN-END:variables
}
