/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package railway;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kk
 */

public class maininterface2 extends javax.swing.JFrame {
    /**
     * Creates new form maininterface2
     */
    String name;
    int nticket;
     String tclass; 
     int charges;
     int tcharges;
     String cnic;
     String t11;String t22 ;String t33;String t44;String t55;String t66;String t77;String t88; String date1  ;
     
   
    public maininterface2(String t1,String t2 ,String t3,String t4,String t5,String t6,String t7,String t8, String date ,String name, String cnic) {
        initComponents();
     
   this.t11=t1; this.t22=t2 ; this.t33=t3; this.t44=t4; this.t55=t5; this.t66=t6; this.t77=t7; this.t88=t8; this.date1=date ;this.name=name;this.cnic=cnic; 
           DefaultTableModel tb=(DefaultTableModel)table.getModel();
   
                   
                   String [] data={t1,t2 ,t3,t4,t5, t6, t7,t8,date};
                
                  tb.addRow(data); 
                  
      dbconnect go=new dbconnect();
            ResultSet rs;
            rs=go.traincharges(t1);
            try {
                if(rs.next())
                {
                    DefaultTableModel tb1=(DefaultTableModel)ratetable.getModel();
   
                   
                   String [] data1={rs.getString("economy"),rs.getString("standard"),rs.getString("ac_business"),rs.getString("ac_sleeper"),rs.getString("polarcar")};
                  tb1.addRow(data1); 
                    
                }
            } catch (SQLException ex) {
                Logger.getLogger(maininterface.class.getName()).log(Level.SEVERE, null, ex);
            } 
          
                 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        trainclass = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        ticket = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        totalc = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ratetable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HAH RAILWAY  RESERVATION SYSTEM");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        back.setBackground(new java.awt.Color(102, 51, 0));
        back.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 810, 160, 60));

        trainclass.setBackground(new java.awt.Color(255, 102, 51));
        trainclass.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        trainclass.setForeground(new java.awt.Color(255, 255, 255));
        trainclass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT TRAIN CLASS", "ECONOMY", "STANDARD", "AC_BUSINESS", "AC_SLEEPER", "POLAR CAR" }));
        trainclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainclassActionPerformed(evt);
            }
        });
        jPanel1.add(trainclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, 380, 80));

        table.setBackground(new java.awt.Color(102, 51, 0));
        table.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        table.setForeground(new java.awt.Color(255, 255, 255));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODE", "TRAIN NAME", "FROM STATION", "TO STATION", "DEPARTURE", "ARRIVAL", "TOTAL TIME", "TOTAL STOPS", "DATE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setSelectionBackground(new java.awt.Color(102, 51, 0));
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 1610, 90));

        ticket.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ticket.setText("ENTER NUMBER OF TICKETS TO BOOK");
        ticket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ticketMouseClicked(evt);
            }
        });
        ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketActionPerformed(evt);
            }
        });
        ticket.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ticketKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ticketKeyTyped(evt);
            }
        });
        jPanel1.add(ticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 510, 380, 70));

        jButton5.setBackground(new java.awt.Color(255, 102, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("NEXT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 710, 380, 90));

        totalc.setBackground(new java.awt.Color(255, 102, 51));
        totalc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        totalc.setText("TOTAL CHARGES: RS.");
        totalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalcActionPerformed(evt);
            }
        });
        jPanel1.add(totalc, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 610, 380, 60));

        ratetable.setBackground(new java.awt.Color(102, 51, 0));
        ratetable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ratetable.setForeground(new java.awt.Color(255, 255, 255));
        ratetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ECONOMY CLASS RATE", "STANDARD CLASS RATE", "AC_BUSINESS CLASS RATE", "AC_SLEEPER", "POLAR CAR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ratetable.setSelectionBackground(new java.awt.Color(102, 51, 0));
        jScrollPane2.setViewportView(ratetable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 1610, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railway/trainlogin.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2060, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
       maininterface go= new maininterface(name,cnic);
       go.setVisible(true);
       dispose();
       
       
    }//GEN-LAST:event_backActionPerformed

    private void trainclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainclassActionPerformed
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_trainclassActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
                       DefaultTableModel tb=(DefaultTableModel)ratetable.getModel();

                       
                       
                       if((trainclass.getSelectedIndex()==0 )&& (!ticket.getText().matches("[0-9]{1,100}") || ticket.getText().trim().isEmpty() ||  ticket.getText().matches("(0){1,100}") || ticket.getText().matches("[a-zA-Z]{1,100}")  ||  ticket.getText().matches("[0-9]&&[a-zA-Z]{1,100}") ))
         {
             JOptionPane.showMessageDialog(null, "SELECT TRAIN CLASS AND ENTER NUMBER OF TICKETS");   
              totalc.setText("TOTAL CHARGES: RS.");
                            ticket.setText("ENTER NUMBER OF TICKETS TO BOOK");

              
         }
        
                       else if(trainclass.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(this,"SELECT TRAIN CLASS","ALERT", 2);
                                        ticket.setText("ENTER NUMBER OF TICKETS TO BOOK");

        }
         
         
         
         
         else if (!ticket.getText().matches("[0-9]{1,100}") || ticket.getText().trim().isEmpty() ||  ticket.getText().matches("(0){1,100}") ||  ticket.getText().matches("[a-zA-Z]{1,100}")  ||  ticket.getText().matches("[0-9]&&[a-zA-Z]{1,100}"))
         {
              JOptionPane.showMessageDialog(null, "ENTER NUMBER OF TICKETS"); 
              totalc.setText("TOTAL CHARGES: RS.");
              ticket.setText("ENTER NUMBER OF TICKETS TO BOOK");

         }
         
         
        
         
         else
         {
              nticket=Integer.parseInt(ticket.getText());
   
     
        if(trainclass.getSelectedIndex()==1)
        {
            tclass=trainclass.getSelectedItem().toString();
           charges= Integer.parseInt((tb.getValueAt(0,0)).toString());
           tcharges=nticket*charges;
           totalc.setText("TOTAL CHARGES: RS."+tcharges);
        }
        else if(trainclass.getSelectedIndex()==2)
        {
                        tclass=trainclass.getSelectedItem().toString();

            charges= Integer.parseInt((tb.getValueAt(0,1)).toString());
             tcharges=nticket*charges;
           totalc.setText("TOTAL CHARGES: RS."+tcharges);
        }
        else if(trainclass.getSelectedIndex()==3)
        {
                        tclass=trainclass.getSelectedItem().toString();

            charges= Integer.parseInt((tb.getValueAt(0,2)).toString());
             tcharges=nticket*charges;
           totalc.setText("TOTAL CHARGES: RS."+tcharges);
        }
        else if(trainclass.getSelectedIndex()==4)
        {
                        tclass=trainclass.getSelectedItem().toString();

            charges= Integer.parseInt((tb.getValueAt(0,3)).toString());
             tcharges=nticket*charges;
           totalc.setText("TOTAL CHARGES: RS."+tcharges);
        }
         else if(trainclass.getSelectedIndex()==5)
        {
                        tclass=trainclass.getSelectedItem().toString();

            charges= Integer.parseInt((tb.getValueAt(0,4)).toString());
             tcharges=nticket*charges;
           totalc.setText("TOTAL CHARGES: RS."+tcharges);
        }
      maininterface3 go=new maininterface3(t11,t22,t33,t44,t55,t66,t77,t88,tclass,nticket, tcharges,date1,name,cnic);
      go.setVisible(true);
   dispose();
         }


    }//GEN-LAST:event_jButton5ActionPerformed

    private void ticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_ticketActionPerformed

    private void ticketKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ticketKeyReleased
        // TODO add your handling code here:
              DefaultTableModel tb=(DefaultTableModel)ratetable.getModel();

                       
            if((trainclass.getSelectedIndex()==0 )&& (!ticket.getText().matches("[0-9]{1,100}") || ticket.getText().trim().isEmpty() ||  ticket.getText().matches("(0){1,100}") || ticket.getText().matches("[a-zA-Z]{1,100}")  ||  ticket.getText().matches("[0-9]&&[a-zA-Z]{1,100}") ))
         {
                            totalc.setText("TOTAL CHARGES: RS.");

              
         }
        
                       else if(trainclass.getSelectedIndex()==0)
        {
                                       totalc.setText("TOTAL CHARGES: RS.");


        }
         
         
         
         
         else if (!ticket.getText().matches("[0-9]{1,100}") || ticket.getText().trim().isEmpty() ||  ticket.getText().matches("(0){1,100}") ||  ticket.getText().matches("[a-zA-Z]{1,100}")  ||  ticket.getText().matches("[0-9]&&[a-zA-Z]{1,100}"))
         {
             
              totalc.setText("TOTAL CHARGES: RS.");
    

         }
         
         
        
         
         else
         {
              nticket=Integer.parseInt(ticket.getText());
   
     
        if(trainclass.getSelectedIndex()==1)
        {
            tclass=trainclass.getSelectedItem().toString();
           charges= Integer.parseInt((tb.getValueAt(0,0)).toString());
           tcharges=nticket*charges;
           totalc.setText("TOTAL CHARGES: RS."+tcharges);
        }
        else if(trainclass.getSelectedIndex()==2)
        {
                        tclass=trainclass.getSelectedItem().toString();

            charges= Integer.parseInt((tb.getValueAt(0,1)).toString());
             tcharges=nticket*charges;
           totalc.setText("TOTAL CHARGES: RS."+tcharges);
        }
        else if(trainclass.getSelectedIndex()==3)
        {
                        tclass=trainclass.getSelectedItem().toString();

            charges= Integer.parseInt((tb.getValueAt(0,2)).toString());
             tcharges=nticket*charges;
           totalc.setText("TOTAL CHARGES: RS."+tcharges);
        }
        else if(trainclass.getSelectedIndex()==4)
        {
                        tclass=trainclass.getSelectedItem().toString();

            charges= Integer.parseInt((tb.getValueAt(0,3)).toString());
             tcharges=nticket*charges;
           totalc.setText("TOTAL CHARGES: RS."+tcharges);
        }
         else if(trainclass.getSelectedIndex()==5)
        {
                        tclass=trainclass.getSelectedItem().toString();

            charges= Integer.parseInt((tb.getValueAt(0,4)).toString());
             tcharges=nticket*charges;
           totalc.setText("TOTAL CHARGES: RS."+tcharges);
        }
     
         }
       
    }//GEN-LAST:event_ticketKeyReleased

    private void totalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalcActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_totalcActionPerformed

    private void ticketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticketMouseClicked
        // TODO add your handling code here:
        ticket.setText("");
    }//GEN-LAST:event_ticketMouseClicked

    private void ticketKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ticketKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ticketKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(maininterface2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(maininterface2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(maininterface2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(maininterface2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new maininterface2("","","","","","","","","","","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable ratetable;
    private javax.swing.JTable table;
    private javax.swing.JTextField ticket;
    private javax.swing.JButton totalc;
    private javax.swing.JComboBox<String> trainclass;
    // End of variables declaration//GEN-END:variables
}
