/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package railway;

import javax.swing.JTextField;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author kk
 */
public class maininterface extends javax.swing.JFrame {
String name;
String cnic;

    /**
     * Creates new form NewJFrame
     */
    public maininterface(String fullname, String cnic ) {
        initComponents();
        this.name=fullname;
        this.cnic=cnic;
       
        signinlabel.setText("ACCOUNT LOGIN: "+fullname.toUpperCase());
        date.setMinSelectableDate(new java.util.Date());
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fromstation = new javax.swing.JComboBox<>();
        tostation = new javax.swing.JComboBox<>();
        date = new com.toedter.calendar.JDateChooser();
        searchtrain = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        signinlabel = new javax.swing.JLabel();
        bnoti = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LOGOUT = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HAH RAILWAY  RESERVATION SYSTEM");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        fromstation.setBackground(new java.awt.Color(102, 51, 0));
        fromstation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fromstation.setForeground(new java.awt.Color(255, 255, 255));
        fromstation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select From Station", "LAHORE JN.", "RAWALPINDI", "KARACHI CANTT", "QUETTA", "PESHAWAR CANTT" }));
        fromstation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromstationActionPerformed(evt);
            }
        });
        jPanel1.add(fromstation, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 339, 55));

        tostation.setBackground(new java.awt.Color(102, 51, 0));
        tostation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tostation.setForeground(new java.awt.Color(255, 255, 255));
        tostation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select to Station", "LAHORE JN.", "RAWALPINDI", "KARACHI CANTT", "QUETTA", "PESHAWAR CANTT" }));
        tostation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tostationActionPerformed(evt);
            }
        });
        jPanel1.add(tostation, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 280, 323, 55));

        date.setBackground(new java.awt.Color(102, 51, 0));
        date.setForeground(new java.awt.Color(102, 51, 0));
        date.setToolTipText("");
        date.setDateFormatString("d MMM, yyyy");
        date.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 680, 55));

        searchtrain.setBackground(new java.awt.Color(102, 51, 0));
        searchtrain.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchtrain.setForeground(new java.awt.Color(255, 255, 255));
        searchtrain.setText("SEARCH TRAINS");
        searchtrain.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchtrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtrainActionPerformed(evt);
            }
        });
        jPanel1.add(searchtrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, 680, 85));

        jButton15.setBackground(new java.awt.Color(0, 204, 204));
        jButton15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("Rate Us");
        jButton15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 850, 173, 94));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railway/bookimg history (1).png"))); // NOI18N
        jButton10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton10.setPreferredSize(new java.awt.Dimension(200, 120));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 750, -1, -1));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railway/train timing (1).png"))); // NOI18N
        jButton9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton9.setPreferredSize(new java.awt.Dimension(200, 120));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 750, -1, -1));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railway/cross (1).png"))); // NOI18N
        jButton8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8.setPreferredSize(new java.awt.Dimension(200, 120));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 750, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("Cancel Tickets");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 1340, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("TRAIN AND TICKET INFORMATION");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 650, 770, 39));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 255, 255));
        jLabel11.setText("Notifications");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 1210, -1, -1));

        signinlabel.setBackground(new java.awt.Color(102, 51, 0));
        signinlabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        signinlabel.setForeground(new java.awt.Color(255, 255, 255));
        signinlabel.setText("   Sign In");
        signinlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signinlabelMouseClicked(evt);
            }
        });
        signinlabel.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                signinlabelInputMethodTextChanged(evt);
            }
        });
        jPanel1.add(signinlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 950, 40));

        bnoti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railway/notification (1).jpg"))); // NOI18N
        bnoti.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bnoti.setPreferredSize(new java.awt.Dimension(200, 120));
        bnoti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnotiActionPerformed(evt);
            }
        });
        jPanel1.add(bnoti, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 750, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 255));
        jLabel10.setText("Book History");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 890, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 255));
        jLabel8.setText("Ticket Cancellation");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 890, -1, -1));

        LOGOUT.setBackground(new java.awt.Color(102, 51, 0));
        LOGOUT.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        LOGOUT.setForeground(new java.awt.Color(255, 255, 255));
        LOGOUT.setText("LOGOUT");
        LOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTActionPerformed(evt);
            }
        });
        jPanel1.add(LOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 255, 255));
        jLabel9.setText("Train Timings");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 890, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 255, 255));
        jLabel12.setText("Notification");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 890, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railway/trainlogin.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2060, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTActionPerformed
        // TODO add your handling code here:
        signin go= new signin();
        go.setVisible(true);
        dispose();
    }//GEN-LAST:event_LOGOUTActionPerformed

    private void signinlabelInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_signinlabelInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_signinlabelInputMethodTextChanged

    private void signinlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinlabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_signinlabelMouseClicked

    private void bnotiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnotiActionPerformed
        // TODO add your handling code here:
        notification go= new notification(name,cnic);
        go.setVisible(true);
        dispose();
    }//GEN-LAST:event_bnotiActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        bookhistory go=new bookhistory(name,cnic);
        go.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        timing go=new timing(name,cnic);
        go.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        cancelt go=new cancelt(name,cnic);
        go.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        rateus go=new rateus(name, cnic);
        go.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void searchtrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtrainActionPerformed
        // TODO add your handling code here:

        if(fromstation.getSelectedIndex()==0 || tostation.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(this, "SELECT STATION", "DESTINATION",2);
        }
        else if(fromstation.getSelectedIndex()==(tostation.getSelectedIndex())){
            JOptionPane.showMessageDialog(this, "FROM AND TO STATION CANNOT BE EQUAL", "DESTINATION",2);

        }
        else if(date.getCalendar()==null)
        {
            JOptionPane.showMessageDialog(this, "SELECT DATE", "ALERT",2);
        }
        else
        {
            String from=fromstation.getSelectedItem().toString();
            String to=tostation.getSelectedItem().toString();
            dbconnect go=new dbconnect();
            ResultSet rs;
            rs=go.searchtrains(from, to);
            try {
                if(rs.next())
                {

                    maininterface1 train= new maininterface1(rs.getString("from_station"),rs.getString("to_station"),name, ((JTextField) date.getDateEditor().getUiComponent()).getText(),cnic);
                    train.setVisible(true);
                    dispose();
                }
            } catch (SQLException ex) {
                Logger.getLogger(maininterface.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_searchtrainActionPerformed

    private void fromstationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromstationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromstationActionPerformed

    private void tostationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tostationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tostationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(maininterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(maininterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(maininterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(maininterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new maininterface("","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LOGOUT;
    private javax.swing.JButton bnoti;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JComboBox<String> fromstation;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton searchtrain;
    private javax.swing.JLabel signinlabel;
    private javax.swing.JComboBox<String> tostation;
    // End of variables declaration//GEN-END:variables
}
