/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package railway;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author kk
 */
public class signup extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
    
    public signup() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        cnic = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        fullname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        answer = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        pass1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        see1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HAH RAILWAY  RESERVATION SYSTEM");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        email.setText("EMAIL(abc@gmail.com)");
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                emailMouseEntered(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, 410, 60));

        phone.setText("PHONE NUMBER(11 digits)");
        phone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phoneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                phoneMouseEntered(evt);
            }
        });
        jPanel2.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 410, 60));

        cnic.setText("CNIC");
        cnic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cnicMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cnicMouseEntered(evt);
            }
        });
        cnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnicActionPerformed(evt);
            }
        });
        jPanel2.add(cnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 410, 60));

        login.setBackground(new java.awt.Color(0, 204, 204));
        login.setText("SIGN IN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel2.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 790, 170, 60));

        fullname.setText("FULL NAME");
        fullname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fullnameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fullnameMouseEntered(evt);
            }
        });
        fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameActionPerformed(evt);
            }
        });
        jPanel2.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 410, 60));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("SIGN UP");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 170, 40));

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setText("GO BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 800, -1, -1));

        answer.setText("Answer");
        answer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                answerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                answerMouseEntered(evt);
            }
        });
        answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerActionPerformed(evt);
            }
        });
        jPanel2.add(answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 710, 410, 60));

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setText("QUESTION: What is your favorite food?");
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 650, 410, 50));
        jPanel2.add(pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 580, 410, 50));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("ENTER PASSWORD");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 560, 140, -1));

        see1.setBackground(new java.awt.Color(0, 204, 204));
        see1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        see1.setForeground(new java.awt.Color(255, 255, 255));
        see1.setText("Show Password");
        see1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                see1ActionPerformed(evt);
            }
        });
        jPanel2.add(see1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 600, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railway/trainlogin.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2060, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
    dbconnect go = new dbconnect();
     String name= "[A-Za-z0-9!@#$%^&*()-_=+{}\\\\[\\\\]|;:'\\\",.<>/?]{1,30}";
    Pattern p=Pattern.compile(name);
    Matcher m=p.matcher(fullname.getText());
    Boolean match=m.find();
    
    String call= "[0-9]{11,11}";
    Pattern p2=Pattern.compile(call);
    Matcher m2=p2.matcher(phone.getText());
    Boolean match2=m2.find();
    
    String mail= "[A-Za-z0-9]{1,15}+(@gmail.com)";
    Pattern p3=Pattern.compile(mail);
    Matcher m3=p3.matcher(email.getText());
    Boolean match3=m3.find();
    
    String id= "[0-9]{13,13}";
    Pattern p4=Pattern.compile(id);
    Matcher m4=p4.matcher(cnic.getText());
    Boolean match4=m4.find();
    
    String password= "[A-Za-z0-9!@#$%^&*()-_=+{}\\\\[\\\\]|;:'\\\",.<>/?]{5,20}";
    Pattern p5=Pattern.compile(password);
    Matcher m5=p5.matcher(pass1.getText());
    Boolean match5=m5.find();
  
   
 if( match&&match2&&match3&&match4&&match5 && go.signup_info(fullname.getText(),phone.getText(), email.getText(), cnic.getText(), pass1.getText(), answer.getText())==1)
   {
        
        JOptionPane.showMessageDialog(this, "ACCOUNT CREATED", "SIGN UP",1);
        signin cl=new signin();
        cl.setVisible(true);
        dispose();
        
        
   }
   else if(!match)
   {
                      JOptionPane.showMessageDialog(this, "Enter Correct Name Expression ", "SIGN UP",2);
 
   }
   else if(!match2)
   {
                      JOptionPane.showMessageDialog(this, "Enter Correct Phone Number ", "SIGN UP",2);
 
   }else if(!match3)
   {
                      JOptionPane.showMessageDialog(this, "Enter Correct Email ", "SIGN UP",2);
 
   }else if(!match4)
   {
                      JOptionPane.showMessageDialog(this, "Enter Correct Cnic ", "SIGN UP",2);
 
   }
   else if(!match5)
   {
                      JOptionPane.showMessageDialog(this, "Enter Correct Password Expression ", "SIGN UP",2);
 
   }
  else if(answer.getText().trim().isEmpty())
   {
                      JOptionPane.showMessageDialog(this, "Enter Answer", "SIGN UP",2);

   }
 else
  {
                            JOptionPane.showMessageDialog(this, "THE SPECIFIC FIELD DATA IS ALREADY BEEN USED", "SIGN UP",2);

  }
    
    }//GEN-LAST:event_loginActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void cnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnicActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        signin back= new signin();
        back.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fullnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullnameMouseClicked
        // TODO add your handling code here
        fullname.setText("");
    }//GEN-LAST:event_fullnameMouseClicked

    private void phoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoneMouseClicked
        // TODO add your handling code here:
                phone.setText("");

    }//GEN-LAST:event_phoneMouseClicked

    private void emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseClicked
        // TODO add your handling code here:
                email.setText("");

    }//GEN-LAST:event_emailMouseClicked

    private void cnicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnicMouseClicked
        // TODO add your handling code here:
                cnic.setText("");

    }//GEN-LAST:event_cnicMouseClicked

    private void fullnameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullnameMouseEntered
        // TODO add your handling code here:
        if(fullname.getText().trim().isEmpty()){
            fullname.setText("FULL NAME");
        }
    }//GEN-LAST:event_fullnameMouseEntered

    private void phoneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoneMouseEntered
        // TODO add your handling code here:
         if(phone.getText().trim().isEmpty()){
            phone.setText("PHONE NUMBER(11 digits)");
        }
    }//GEN-LAST:event_phoneMouseEntered

    private void emailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseEntered
        // TODO add your handling code here:
         if(email.getText().trim().isEmpty()){
            email.setText("EMAIL(eg. abc@gmail.com)");
        }
    }//GEN-LAST:event_emailMouseEntered

    private void cnicMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnicMouseEntered
        // TODO add your handling code here:
         if(cnic.getText().trim().isEmpty()){
           cnic.setText("CNIC");
         }
    }//GEN-LAST:event_cnicMouseEntered

    private void answerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_answerMouseClicked
        // TODO add your handling code here:
        answer.setText("");
    }//GEN-LAST:event_answerMouseClicked

    private void answerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_answerMouseEntered
        // TODO add your handling code here:
         if(answer.getText().trim().isEmpty()){
            answer.setText("Answer");
         }
    }//GEN-LAST:event_answerMouseEntered

    private void answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerActionPerformed

    private void see1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_see1ActionPerformed
        // TODO add your handling code here:
        if(see1.isSelected()){
            pass1.setEchoChar((char)0);
        }
        else
        {
            pass1.setEchoChar('*');
        }
    }//GEN-LAST:event_see1ActionPerformed

    private void fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answer;
    private javax.swing.JTextField cnic;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fullname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JTextField phone;
    private javax.swing.JCheckBox see1;
    // End of variables declaration//GEN-END:variables
}
